variables:
  SCCACHE_DIR: $(Pipeline.Workspace)/.cache/sccache 
  SCCACHE_VERSION: 0.2.9
trigger:
- master
jobs:
- job: envs
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: none
    - script: export
      displayName: List variables
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$CARGO_HOME"
      name: cargo_home
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$(cargo --version)"
      name: cargo_version
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$RUSTUP_HOME"
      name: rustup_home
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: envs
  # variables:
    # ENVS_CARGO_HOME: $[dependencies.envs.outputs['cargo_home.val']]
    # ENVS_CARGO_VERSION: $[dependencies.envs.outputs['cargo_version.val']]
    # ENVS_RUSTUP_HOME: $[dependencies.envs.outputs['rustup_home.val']]
  steps:
    - checkout: self
      fetchDepth: 1
    - task: CacheBeta@0
      inputs:
        key: |
          rustup
          $(Agent.OS)
          $(Agent.OSArchitecture)
          $(ENVS_CARGO_VERSION)
        path: $(ENVS_RUSTUP_HOME)
        cacheHitVar: CACHE_RESTORED_RUSTUP
      displayName: Cache Rustup
      condition: false
    - task: CacheBeta@0
      inputs:
        key: |
          sccache
          rev.1
          $(Agent.OS)
          $(Agent.OSArchitecture)
        path: $(SCCACHE_DIR)
        cacheHitVar: CACHE_RESTORED_SCCACHE
      displayName: Cache sccache
    - script: |
        curl -sSfLO https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz
        tar -xvf sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz
        echo "##vso[task.prependpath]$PWD/sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl"
      displayName: Setup sccache
    - script: rustup component add clippy
      displayName: Setup Clippy
    - script: RUSTC_WRAPPER="$(command -v sccache)" cargo -v build
      displayName: Build
    - script: RUSTC_WRAPPER="$(command -v sccache)" cargo clippy
      displayName: Clippy
