variables:
  RUSTC_WRAPPER: sccache
  SCCACHE_VERSION: 0.2.9
trigger:
  - master
stages:
  - stage:
    displayName: Prepare
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - checkout: none
          - script: |
              curl -sSfLO https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz
              tar -xvf sccache-${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz
            displayName: Download sccache for Linux
            workingDirectory: $(Pipeline.Workspace)
          - publish: $(Pipeline.Workspace)/sccache-$(SCCACHE_VERSION)-x86_64-unknown-linux-musl/sccache
            artifact: sccache-linux
          - script: |
              curl -sSfLO https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/sccache-${SCCACHE_VERSION}-x86_64-pc-windows-msvc.tar.gz
              tar -xvf sccache-${SCCACHE_VERSION}-x86_64-pc-windows-msvc.tar.gz
            displayName: Download sccache for Windows
            workingDirectory: $(Pipeline.Workspace)
          - publish: $(Pipeline.Workspace)/sccache-$(SCCACHE_VERSION)-x86_64-pc-windows-msvc/sccache.exe
            artifact: sccache-windows
  - stage:
    displayName: Build
    jobs:
      - job:
        displayName: Linux
        pool:
          vmImage: 'ubuntu-16.04'
        variables:
          SCCACHE_DIR: $(Pipeline.Workspace)/.cache/sccache
        steps:
          - checkout: self
            fetchDepth: 1
          - download: current
            artifact: sccache-linux
          - script: echo "##vso[task.prependpath]$PWD/sccache-linux"
            displayName: Setup sccache
            workingDirectory: $(Pipeline.Workspace)
          - script: cargo -v build
            displayName: Build
          - script: sccache --show-stats
            displayName: Show sccache stats
      - job:
        displayName: Windows
        pool:
          vmImage: 'windows-latest'
        variables:
          RUSTUP_HOME: $(Pipeline.Workspace)\.rustup
          CARGO_HOME: $(Pipeline.Workspace)\.cargo
          SCCACHE_DIR: $(Pipeline.Workspace)\Mozilla\sccache
        steps:
          - download: current
            artifact: sccache-windows
          - powershell: |
              Invoke-WebRequest -OutFile rustup-init.exe -Uri https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
              .\rustup-init -vy
              echo "##vso[task.prependpath]$Env:CARGO_HOME\bin"
            displayName: Download Rust
          - script: echo ##vso[task.prependpath]%CD%\sccache-windows
            displayName: Setup sccache
            workingDirectory: $(Pipeline.Workspace)
          - script: cargo -v build
            displayName: Build
          - script: sccache --show-stats
            displayName: Show sccache stats
  - stage:
    displayName: Check
    jobs:
      - job:
        displayName: Linux
        pool:
          vmImage: 'ubuntu-16.04'
        variables:
          SCCACHE_DIR: $(Pipeline.Workspace)/.cache/sccache
        steps:
          - checkout: self
          - download: current
            artifact: sccache-linux
          - script: echo "##vso[task.prependpath]$PWD/sccache-linux"
            displayName: Setup sccache
            workingDirectory: $(Pipeline.Workspace)
          - script: rustup component add clippy
            displayName: Setup Clippy
          - script: cargo clippy
            displayName: Clippy
          - script: sccache --show-stats
            displayName: Show sccache stats
      - job:
        displayName: Windows
        pool:
          vmImage: 'windows-latest'
        variables:
          RUSTUP_HOME: $(Pipeline.Workspace)\.rustup
          CARGO_HOME: $(Pipeline.Workspace)\.cargo
          SCCACHE_DIR: $(Pipeline.Workspace)\Mozilla\sccache
        steps:
          - download: current
            artifact: sccache-windows
          - powershell: |
              Invoke-WebRequest -OutFile rustup-init.exe -Uri https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
              .\rustup-init -vy
              echo "##vso[task.prependpath]$Env:CARGO_HOME\bin"
            displayName: Download Rust
          - script: rustup component add clippy
            displayName: Setup Clippy
          - script: echo ##vso[task.prependpath]%CD%\sccache-windows
            displayName: Setup sccache
            workingDirectory: $(Pipeline.Workspace)
          - script: cargo clippy
            displayName: Clippy
          - script: sccache --show-stats
            displayName: Show sccache stats
