trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: rust:1.36

steps:
- script: rustup component add clippy
  displayName: Setup Clippy
- script: cargo build
  displayName: Build
- script: cargo clippy
  displayName: Clippy
