variables:
  # RUSTC_WRAPPER: sccache
  SCCACHE_VERSION: 0.2.9
trigger:
  - master
jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      SCCACHE_DIR: $(Pipeline.Workspace)/.cache/sccache
    steps:
      - checkout: self
        fetchDepth: 1
      - script: rustup component add clippy
        displayName: Setup Clippy
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
  - job:
    displayName: Windows
    pool:
      vmImage: 'windows-latest'
    variables:
      SCCACHE_DIR: $(Pipeline.Workspace)\Mozilla\sccache
    steps:
      - checkout: self
        fetchDepth: 1
      - script: rustup component add clippy
        displayName: Setup Clippy
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
