variables:
  CARGO_CACHE_FOLDER: $(Pipeline.Workspace)/.cargo
  RUSTUP_CACHE_FOLDER: $(Pipeline.Workspace)/.rustup
  SCCACHE_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/sccache
trigger:
- master
pool:
  vmImage: 'ubuntu-16.04'
container: rust:1.36
steps:
- script: export
  displayName: List variables
- script: rustup component add clippy
  displayName: Setup Clippy
- script: cargo build
  displayName: Build
- script: cargo clippy
  displayName: Clippy
- script: ls -la $(CARGO_HOME)
  displayName: ls CARGO_HOME
  continueOnError: true
- script: ls -la $(CARGO_CACHE_FOLDER)
  displayName: ls CARGO_CACHE_FOLDER
  continueOnError: true
- script: ls -la $(RUSTUP_CACHE_FOLDER)
  displayName: ls RUSTUP_CACHE_FOLDER
  continueOnError: true
- script: ls -la $(RUSTUP_HOME)
  displayName: ls RUSTUP_HOME
  continueOnError: true
- script: ls -la $(/usr/local/cargo/bin)
  displayName: ls /usr/local/cargo/bin
  continueOnError: true
