trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: rust:1.36

stages:
- stage: Prepare
  steps:
  - script: rustup component add clippy
- stage: Build
  steps:
  - script: cargo build
- stage: lint
  steps:
  - script: cargo clippy
