variables:
  CI: true
trigger:
  - master
  - refs/tags/v*
jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    condition: false
    steps:
      - checkout: self
        fetchDepth: 1
      - script: export
      - script: rustup component add clippy
        displayName: Setup Rust
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
  - job:
    displayName: Docker
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: export
      - script: docker-compose build
        displayName: Build
  - job:
    displayName: Windows
    pool:
      vmImage: 'windows-latest'
    condition: false
    steps:
      - checkout: self
        fetchDepth: 1
      - script: rustup component add clippy
        displayName: Setup Rust
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
  - job:
    displayName: macOS
    pool:
      vmImage: 'macOS-latest'
    variables:
      RUSTUP_HOME: $(Pipeline.Workspace)/.rustup
      CARGO_HOME: $(Pipeline.Workspace)/.cargo
    condition: false
    steps:
      - checkout: self
        fetchDepth: 1
      - script: export
      - script: |
          curl -sSf https://sh.rustup.rs | bash -s -- -v -y --no-modify-path
          $(CARGO_HOME)/bin/rustup component add clippy
          echo "##vso[task.prependpath]$(CARGO_HOME)/bin"
        displayName: Setup Rust
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
  - job:
    displayName: macOS
    pool:
      vmImage: 'macOS-latest'
    variables:
      RUSTUP_HOME: $(Pipeline.Workspace)/.rustup
      CARGO_HOME: $(Pipeline.Workspace)/.cargo
    steps:
      - checkout: self
        fetchDepth: 1
      - script: export
      - script: echo tag event
        displayName: is tag event by condition syntax
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
      - script: '[[ $BUILD_SOURCEBRANCH =~ ^refs/tags/v ]] && echo tag event || echo not tag event'
        displayName: is tag event by bash
      - script: |
          echo system
          git config --system credential.helper
          echo global
          git config --global credential.helper
          echo local
          git config credential.helper
          echo unset local
          git config --system --unset credential.helper
          echo local
          git config credential.helper || echo failed locall
          echo system
          git config --system credential.helper || echo failed system
          echo cat
          cat .git/config
