variables:
  # RUSTC_WRAPPER: sccache
  SCCACHE_VERSION: 0.2.9
trigger:
  - master
jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: rustup component add clippy
        displayName: Setup Rust
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
  - job:
    displayName: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: rustup component add clippy
        displayName: Setup Rust
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
  - job:
    displayName: macOS
    pool:
      vmImage: 'macOS-latest'
    variables:
      RUSTUP_HOME: $(Pipeline.Workspace)/.rustup
      CARGO_HOME: $(Pipeline.Workspace)/.cargo
    steps:
      - checkout: self
        fetchDepth: 1
      - script: |
          curl -sSf https://sh.rustup.rs | bash -s -- --help
          $(CARGO_HOME)/bin/rustup component add clippy
          echo "##vso[task.prependpath]$(CARGO_HOME)/bin"
        displayName: Setup Rust
      - script: cargo -v build
        displayName: Build
      - script: cargo clippy
        displayName: Clippy
