variables:
  SCCACHE_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/sccache
trigger:
- master
pool:
  vmImage: 'ubuntu-16.04'
container: rust:1.36
steps:
- script: export
  displayName: List variables
  enabled: false
- script: rustup component add clippy
  displayName: Setup Clippy
  enabled: false
- script: cargo build
  displayName: Build
  enabled: false
- script: cargo clippy
  displayName: Clippy
  enabled: false
- script: rm -rf $(CARGO_HOME)/.cargo/registry/src
  displayName: Reduce cargo cache
  enabled: false
- script: echo $MYVAL
  displayName: echo MYVAL
  env:
    MYVAL: $[format('{0}', variables['RUST_VERSION'])]
