variables:
  SCCACHE_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/sccache
  CONTAINER_VERSION: 1.36
trigger:
- master
jobs:
- job: envs
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: none
    - script: export
      displayName: List variables
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$CARGO_HOME"
      name: cargo_home
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$(cargo --version)"
      name: cargo_version
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$RUSTUP_HOME"
      name: rustup_home
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: envs
  variables:
    ENVS_CARGO_HOME: $[dependencies.envs.outputs['cargo_home.val']]
    ENVS_CARGO_VERSION: $[dependencies.envs.outputs['cargo_version.val']]
    ENVS_RUSTUP_HOME: $[dependencies.envs.outputs['rustup_home.val']]
  steps:
    - task: CacheBeta@0
      inputs:
        key: |
          cargo
          $(Agent.OS)
          $(Agent.OSArchitecture)
          $($[dependencies.envs.outputs['cargo_version.val']])
        path: $($[dependencies.envs.outputs['cargo_home.val']]))
    - task: CacheBeta@0
      inputs:
        key: |
          rustup
          $(Agent.OS)
          $(Agent.OSArchitecture)
          $($[dependencies.envs.outputs['cargo_version.val']])
        path: $($[dependencies.envs.outputs['rustup_home.val']])
    - script: rustup component add clippy
      displayName: Setup Clippy
    - script: cargo build
      displayName: Build
    - script: cargo clippy
      displayName: Clippy
    - script: rm -rf $(CARGO_HOME)/.cargo/registry/src
      displayName: Reduce cargo cache
- job: bash_env
  condition: false
  pool:
    vmImage: 'ubuntu-16.04'
  container: rust:$(CONTAINER_VERSION)
  steps:
    - script: export
      displayName: List variables
    - script: echo "##vso[task.setvariable variable=val;isOutput=true]$CARGO_HOME"
      name: cargo_home
- job:
  dependsOn: bash_env
  condition: false
  pool:
    vmImage: 'ubuntu-16.04'
  container: rust:$(CONTAINER_VERSION)
  variables:
    AA: $[dependencies.bash_env.outputs['cargo_home.val']]
  steps:
    - script: echo "$AA"
      enabled: false
    - task: CacheBeta@0
      inputs:
        key: |
          cargo
          $(Agent.OS)
          $(Agent.OSArchitecture)
        path: $(CARGO_CACHE_FOLDER)
      enabled: false
    - script: rustup component add clippy
      displayName: Setup Clippy
    - script: cargo build
      displayName: Build
    - script: cargo clippy
      displayName: Clippy
    - script: rm -rf $(CARGO_HOME)/.cargo/registry/src
      displayName: Reduce cargo cache
