[github]
host = "https://api.github.com/graphql"

[[oss]]
repo = "jwilm/alacritty"
version = "v0.3.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "tmux/tmux"
version = "2.8"
prerelease = false
check_method = "release"

[[oss]]
repo = "cmderdev/cmder"
version = "v1.3.11"
prerelease = false
check_method = "release"

[[oss]]
repo = "vuetifyjs/vuetify"
version = "v1.5.11"
prerelease = false
check_method = "release"

[[oss]]
repo = "vuejs/vue"
version = "v2.6.10"
prerelease = false
check_method = "release"

[[oss]]
repo = "git-lfs/git-lfs"
version = "v2.7.1"
prerelease = false
check_method = "release"

[[oss]]
repo = "rust-lang/rust"
version = "1.34.0"
prerelease = false
check_method = "tag"

[[oss]]
repo = "graphql-rust/juniper"
version = "juniper-0.11.1"
prerelease = false
check_method = "tag"

[[oss]]
repo = "TeXitoi/structopt"
version = "v0.2.15"
prerelease = false
check_method = "tag"

[[oss]]
repo = "hyperium/hyper"
version = "v0.12.25"
prerelease = false
check_method = "release"

[[oss]]
repo = "bootstrap-vue/bootstrap-vue"
version = "v2.0.0-rc.18"
prerelease = true
check_method = "release"

[[oss]]
repo = "diesel-rs/diesel"
version = "v1.4.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "protocolbuffers/protobuf"
version = "v3.7.1"
prerelease = false
check_method = "release"

[[oss]]
repo = "Yelp/dumb-init"
version = "v1.2.2"
prerelease = false
check_method = "release"

[[oss]]
repo = "stepancheg/rust-protobuf"
version = "v2.4.2"
prerelease = false
check_method = "tag"

[[oss]]
repo = "stepancheg/grpc-rust"
version = "v0.6.1"
prerelease = false
check_method = "tag"

[[oss]]
repo = "tokio-rs/tokio"
version = "tokio-threadpool-0.1.13"
prerelease = false
check_method = "tag"

[[oss]]
repo = "improbable-eng/grpc-web"
version = "v0.9.1"
prerelease = false
check_method = "release"

[[oss]]
repo = "mobile-shell/mosh"
version = "mosh-1.3.2"
prerelease = false
check_method = "release"

[[oss]]
repo = "rust-lang-nursery/futures-rs"
version = "0.1.26"
prerelease = false
check_method = "release"

[[oss]]
repo = "grpc/grpc-web"
version = "1.0.4"
prerelease = false
check_method = "release"

[[oss]]
repo = "Microsoft/TypeScript"
version = "v3.4.3"
prerelease = false
check_method = "release"

[[oss]]
repo = "nodejs/node"
version = "v11.14.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "TypeStrong/ts-node"
version = "v8.0.3"
prerelease = false
check_method = "release"

[[oss]]
repo = "klaussinani/signale"
version = "v1.4.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "rust-lang-nursery/failure"
version = "0.1.5"
prerelease = false
check_method = "tag"

[[oss]]
repo = "amanusk/s-tui"
version = "v0.8.3"
prerelease = true
check_method = "release"

[[oss]]
repo = "Shougo/deoplete.nvim"
version = "5.0"
prerelease = false
check_method = "tag"

[[oss]]
repo = "Shougo/dein.vim"
version = "2.0"
prerelease = false
check_method = "tag"

[[oss]]
repo = "zxqfl/tabnine-sublime"
version = "1.0.2"
prerelease = false
check_method = "release"

[[oss]]
repo = "tomaka/winit"
version = "v0.18.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "SublimeText/sublime_lib"
version = "v1.3.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "vuejs/ui"
version = "v0.9.1"
prerelease = false
check_method = "release"

[[oss]]
repo = "peco/peco"
version = "v0.5.3"
prerelease = false
check_method = "release"

[[oss]]
repo = "dylanaraps/neofetch"
version = "6.0.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "ApolloZhu/Dynamic-Dark-Mode"
version = "1.1.4"
prerelease = false
check_method = "release"

[[oss]]
repo = "macports/macports-base"
version = "v2.5.4"
prerelease = false
check_method = "release"

[[oss]]
repo = "rust-lang/rust-enhanced"
version = "v2.19.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "dutchcoders/transfer.sh"
version = "v1.0.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "sailorhg/fairyfloss"
version = "v0.2.0"
prerelease = false
check_method = "tag"

[[oss]]
repo = "ffftp/ffftp"
version = "v3.7"
prerelease = false
check_method = "release"

[[oss]]
repo = "sony/nnabla"
version = "v1.0.15"
prerelease = false
check_method = "release"

[[oss]]
repo = "netdata/netdata"
version = "v1.13.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "tootsuite/mastodon"
version = "v2.8.0"
prerelease = false
check_method = "release"

[[oss]]
repo = "r888888888/danbooru"
version = "production-2019.03.06-014802-utc"
prerelease = false
check_method = "tag"

[[oss]]
repo = "google/iosched"
version = "2017"
prerelease = false
check_method = "tag"

[[oss]]
repo = "gitbucket/gitbucket"
version = "4.31.2"
prerelease = false
check_method = "release"

[[oss]]
repo = "github/hub"
version = "v2.11.1"
prerelease = false
check_method = "release"

[[oss]]
repo = "nagadomi/waifu2x"
version = "v0.13.2"
prerelease = false
check_method = "release"
